compmap/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls')),
]

main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # URLs curso
    url(r'^curso/$', views.CursoListView.as_view(), name='curso-list'),
    url(r'^curso/(?P<pk>\d+)/$', views.CursoDetailView.as_view(),
        name='curso-detail'),
    url(r'^curso/add/$', views.CursoCreateView.as_view(), name='curso-add'),
    url(r'^curso/(?P<pk>\d+)/edit/$', views.CursoUpdateView.as_view(),
        name='curso-edit'),
    url(r'^curso/(?P<pk>\d+)/delete/$', views.CursoDeleteView.as_view(),
        name='curso-delete'),

    # URLs IES
    url(r'^ies/$', views.IESListView.as_view(), name='ies-list'),
    url(r'^ies/add/$', views.IESCreateView.as_view(), name='ies-add'),
    url(r'^ies/(?P<pk>\d+)/$', views.IESDetailView.as_view(),
        name='ies-detail'),
    url(r'^ies/(?P<pk>\d+)/edit/$', views.IESUpdateView.as_view(),
        name='ies-edit'),
    url(r'^ies/(?P<pk>\d+)/delete$', views.IESDeleteView.as_view(),
        name='ies-delete'),

    # URLs Mapa
    url(r'^mapa/$', views.map_view, name='map-view'),
]

main/models.py
# coding: utf-8
from django.urls import reverse
from django.utils import timezone

from django.db import models


# TODO Adicionar endereco da instituicao
class IntituicaoEnsinoSuperior(models.Model):
    # Organizacao Academica
    UNIVERSIDADE = 'UNI'
    CENTRO_UNIVERSITARIO = 'CENT_UNI'
    FACULDADE = 'FACUL'
    INSTITUTO_FEDERAL = 'INST_FED'
    ORG_ACADEMICA_CHOICES = (
        (UNIVERSIDADE, 'Universidade'),
        (CENTRO_UNIVERSITARIO, 'Centro Universitário'),
        (FACULDADE, 'Faculdade'),
        (INSTITUTO_FEDERAL, 'Instituto Federal'),
    )

    # Categoria administrativa
    REDE_PUBLICA = 'PUB'
    REDE_PRIVADA = 'PRI'
    REDE_CHOICES = (
        (REDE_PUBLICA, 'Pública'),
        (REDE_PRIVADA, 'Privada'),
    )
    ADM_FEDERAL = 'FED'
    ADM_ESTADUAL = 'EST'
    ADM_MUNICIPAL = 'MUN'
    ADM_PRIVADA = 'PRI'
    DEPARTAMENTO_ADM_CHOICES = (
        (ADM_FEDERAL, 'Federal'),
        (ADM_ESTADUAL, 'Estadual'),
        (ADM_MUNICIPAL, 'Municipal'),
        (ADM_PRIVADA, 'Privada'),
    )

    nome_IES = models.CharField('Nome', max_length=100, null=False)
    sigla_IES = models.CharField('Sigla', max_length=10, null=False)
    email_IES = models.EmailField('Email', max_length=32, null=False)
    cod_mant = models.ForeignKey('Mantenedora', on_delete=models.CASCADE,
                                 default=1)
    organizacao_academica = models.CharField('Organização Acadêmica',
                                             max_length=10,
                                             choices=ORG_ACADEMICA_CHOICES,
                                             default=UNIVERSIDADE, null=False)
    rede = models.CharField('Rede', max_length=3, choices=REDE_CHOICES,
                            default=REDE_PUBLICA, null=False)
    departamento_administrativo = models.CharField(
        'Departamento Administrativo', max_length=3,
        choices=DEPARTAMENTO_ADM_CHOICES, default=ADM_ESTADUAL, null=False)
    cep = models.IntegerField('CEP', default=00000000, null=False)

    def get_absolute_url(self):
        return reverse('main:ies-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nome_IES


class Mantenedora(models.Model):
    nome_mant = models.CharField('Nome', max_length=80, null=False)

    def __str__(self):
        return self.nome_mant


# TODO Adicionar endereço onde o curso é ofertado
class Curso(models.Model):
    # Modalidades possiveis para o curso
    PRESENCIAL = 'PRE'
    EAD = 'EAD'
    MODALIDADE_CHOICES = (
        (PRESENCIAL, 'Presencial'),
        (EAD, 'Ensino à distância'),
    )

    # Nivel do curso
    BACHARELADO = 'BACH'
    LICENCIATURA = 'LICEN'
    TECNICO = 'TEC'
    NAO_APLICAVEL = 'NAP'
    NIVEL_CHOICES = (
        (BACHARELADO, 'Bacharelado'),
        (LICENCIATURA, 'Licenciatura'),
        (TECNICO, 'Técnico'),
        (NAO_APLICAVEL, 'Não Aplicável'),
    )

    # Periodo do curso
    MATUTINO = 'M'
    VESPERTINO = 'V'
    NOTURNO = 'N'
    INTEGRAL = 'I'
    VESPERTINO_NOTURNO = 'VN'
    PERIODO_CHOICES = (
        (MATUTINO, 'Matutino'),
        (VESPERTINO, 'Vespertino'),
        (NOTURNO, 'Noturno'),
        (INTEGRAL, 'Integral'),
        (VESPERTINO_NOTURNO, 'Vespertino/Noturno'),
    )

    nome_curso = models.CharField('Nome do Curso', max_length=200, null=False)
    data_inicio_oferta = models.DateField('Data de início da oferta',
                                          default=timezone.now, null=False)
    cod_IES = models.ForeignKey('IntituicaoEnsinoSuperior',
                                on_delete=models.CASCADE, default=1)
    carga_horaria = models.IntegerField('Carga Horária', default=2400,
                                        null=False)
    modalidade = models.CharField(max_length=3, choices=MODALIDADE_CHOICES,
                                  default=PRESENCIAL, null=False)
    nivel_curso = models.CharField(max_length=5, choices=NIVEL_CHOICES,
                                   default=BACHARELADO, null=False)
    periodo = models.CharField(max_length=2, choices=PERIODO_CHOICES,
                               default=NOTURNO, null=False)
    curso_gratuito = models.BooleanField('Curso Gratuito', default=True)
    num_vagas = models.IntegerField('Número de vagas', default=40, null=False)
    possui_acessabilidade = models.BooleanField('Possui Acessabilidade',
                                                default=False)

    def get_absolute_url(self):
        return reverse('main:curso-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nome_curso

main/forms.py
from django import forms
from .models import Curso


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso
        fields = (
            'nome_curso', 'data_inicio_oferta', 'cod_IES', 'carga_horaria',
            'modalidade', 'nivel_curso', 'periodo', 'curso_gratuito',
            'num_vagas',
            'possui_acessabilidade')

main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls.base import reverse_lazy
from django.views import generic
from .models import Curso, IntituicaoEnsinoSuperior


# TODO refactor code for class based views (50%)
# TODO Add Mantenedora views
# TODO Add Map views


def index(request):
    return render(request, 'main/index.html')


# views Cursos
class CursoListView(generic.ListView):
    template_name = 'main/cursos.html'
    context_object_name = 'cursos'
    model = Curso
    paginate_by = 10

    def get_queryset(self):
        try:
            q = self.request.GET.get('q')
            if q is None:
                q = ''
        except:
            q = ''
        if q != '':
            object_list = self.model.objects.filter(nome_curso__icontains=q)
        else:
            object_list = self.model.objects.all()
        return object_list


class CursoCreateView(generic.CreateView):
    model = Curso
    fields = ['nome_curso', 'data_inicio_oferta', 'cod_IES', 'carga_horaria',
              'modalidade', 'nivel_curso', 'periodo', 'curso_gratuito',
              'num_vagas', 'possui_acessabilidade']
    template_name = 'main/curso_create_form.html'


class CursoUpdateView(generic.UpdateView):
    model = Curso
    fields = ['nome_curso', 'data_inicio_oferta', 'cod_IES', 'carga_horaria',
              'modalidade', 'nivel_curso', 'periodo', 'curso_gratuito',
              'num_vagas', 'possui_acessabilidade']
    template_name = 'main/curso_update_form.html'


class CursoDetailView(generic.DetailView):
    model = Curso
    template_name = 'main/curso_detail.html'


class CursoDeleteView(generic.DeleteView):
    model = Curso
    success_url = reverse_lazy('curso-list')


# views IES

class IESListView(generic.ListView):
    model = IntituicaoEnsinoSuperior
    template_name = 'main/ies.html'
    paginate_by = 10

    def get_queryset(self):
        try:
            q = self.request.GET.get('q')
            if q is None:
                q = ''
        except:
            q = ''
        if q != '':
            object_list = self.model.objects.filter(nome_IES__icontains=q)
        else:
            object_list = self.model.objects.all()
        return object_list


class IESCreateView(generic.CreateView):
    model = IntituicaoEnsinoSuperior
    fields = ['nome_IES', 'sigla_IES', 'email_IES', 'cod_mant',
              'organizacao_academica', 'rede', 'departamento_administrativo',
              'cep']
    template_name = 'main/ies_create_form.html'


class IESDetailView(generic.DetailView):
    model = IntituicaoEnsinoSuperior
    context_object_name = 'ies'
    template_name = 'main/ies_detail.html'


class IESUpdateView(generic.UpdateView):
    model = IntituicaoEnsinoSuperior
    fields = ['nome_IES', 'sigla_IES', 'email_IES', 'cod_mant',
              'organizacao_academica', 'rede', 'departamento_administrativo',
              'cep']
    template_name = 'main/ies_update_form.html'


class IESDeleteView(generic.DeleteView):
    model = IntituicaoEnsinoSuperior
    success_url = reverse_lazy('ies-list')
    template_name = 'main/ies_confirm_delete.html'


# map

def map_view(request):
    return render(request, 'main/map.html')

main/templates/main/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
          crossorigin="anonymous">
    <link rel="stylesheet" type="text/css"
          href="{% static 'main/style.css' %}"/>
    <link href='https://fonts.googleapis.com/css?family=Satisfy'
          rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <title>{% block title %}CompMap{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#topNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'main:index' %}">CompMap</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavbar">
            <ul class="nav navbar-nav">
                <li class="{% block index_active %}{% endblock %}">
                    <a href="{% url 'main:index' %}">
                        <i class="fas fa-home"></i>&nbsp; Home
                    </a>
                </li>
                <li class="{% block cursos_active %}{% endblock %}">
                    <a href="{% url 'main:curso-list' %}">
                        <i class="fas fa-graduation-cap"></i>&nbsp; Cursos
                    </a>
                </li>
                <li class="{% block ies_active %}{% endblock %}">
                    <a href="{% url 'main:ies-list' %}">
                        <i class="fas fa-university"></i>&nbsp; Instituições
                    </a>
                </li>
                <li class="{% block map_active %}{% endblock %}">
                    <a href="{% url 'main:map-view' %}">
                        <i class="fas fa-map-marker"></i>&nbsp; Mapa
                    </a>
                </li>
            </ul>
            <!--<form class="navbar-form navbar-left" role="search" method="get" action="{% url 'main:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>-->
            <ul class="nav navbar-nav navbar-right">
                <li class="{% block login_active %}{% endblock %}">
                    <a href="#">
                        <i class="fas fa-sign-in-alt"></i>&nbsp; Acesso
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% block content %}
{% endblock %}
<!-- Script import -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script defer
        src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/curso_confirm_delete.html
{% extends 'main/base.html' %}

{% block title %}CompMap | Excluir Curso{% endblock %}

{% block content %}
<div class="container text-center col-md-6" style="display: table;">
    <div class="panel panel-danger vertical-centered">
        <div class="panel-heading">
            <i class="fas fa-exclamation-triangle"></i>&nbsp; Exclusão de Curso
        </div>
        <div class="panel-body">
            <form action="" method="post">{% csrf_token %}
                <p>Tem certeza que deseja excluir "{{ object }}"?</p>
                <input class="btn btn-danger btn-lg" type="submit"
                       value="Confirmar"/>
                &nbsp;
                <a class="btn btn-default btn-lg"
                   href="{% url 'main:curso-detail' pk=curso.pk %}">
                    Cancelar
                </a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/curso_create_form.html
{% extends 'main/base.html' %}

{% block title %} CompMap | Adicionar Instituição {% endblock %}

{% block content %}
<div class="container">
    <form method="post" class="form-group">
        {% csrf_token %}
        <legend>Adicionar Curso</legend>
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">
            <i class="fas fa-save"></i>&nbsp; Salvar
        </button>
        <a class="btn btn-danger" href="{% url 'main:curso-list' %}">
            <i class="fas fa-times"></i>&nbsp;Cancelar
        </a>
    </form>
</div>
{% endblock %}

main/templates/main/curso_detail.html
{% extends 'main/base.html' %}

{% block title %}CompMap | Detalhes do Curso{% endblock %}

{% block content %}

<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <i class="fas fa-graduation-cap"></i>&nbsp;
            <a href="{% url 'main:curso-detail' pk=curso.pk %}">
                {{ curso.nome_curso }}
            </a>
            <a class="pull-right" href="{% url 'main:curso-list' %}">
                <i class="fas fa-arrow-left"></i>&nbsp;Voltar
            </a>
        </div>
        <div class="panel-body">
            <p><b>Instituição responsável:&nbsp;</b>{{ curso.cod_IES }}</p>
            <p><b>Nível:&nbsp;</b>
                {% if curso.nivel_curso == 'BACH' %}
                Bacharelado
                {% elif curso.nivel_curso == 'LICEN' %}
                Licenciatura
                {% elif curso.nivel_curso == 'TEC' %}
                Tecnólogo
                {% else %}
                Não Aplicável
                {% endif %}
            </p>
            <p><b>Modalidade:&nbsp;</b>
                {% if curso.modalidade == 'PRE' %}
                Presencial
                {% else %}
                Ensino à Distância
                {% endif %}
            </p>
            <p><b>Período:&nbsp;</b>
                {% if curso.periodo == 'N' %}
                Noturno
                {% elif curso.periodo == 'M' %}
                Matutino
                {% elif curso.periodo == 'V' %}
                Vespertino
                {% elif curso.periodo == 'I' %}
                Integral
                {% else %}
                Vespertino/Noturno
                {% endif %}
            </p>
            <p><b>Carga horária:&nbsp</b>{{ curso.carga_horaria }}</p>
            <p><b>Número de vagas:&nbsp</b>{{ curso.num_vagas }}</p>
            <p>
                <b>Gratuito:&nbsp;</b>
                {% if curso.curso_gratuito %}
                <i class="fas fa-check" style="color: #5cb85c;"></i>
                {% else %}
                <i class="fas fa-times" style="color: #d9534f;"></i>
                {% endif %}
            </p>
            <p>
                <b>Possui acessabilidade:&nbsp;</b>
                {% if curso.possui_acessabilidade %}
                <i class="fas fa-check" style="color: #5cb85c;"></i>
                {% else %}
                <i class="fas fa-times danger" style="color: #d9534f;"></i>
                {% endif %}
            </p>
        </div>
    </div>
    <hr>
    <div class="row">
        &nbsp;&nbsp;
        <a class="btn btn-default"
           href="{% url 'main:curso-edit' pk=curso.pk %}">
            <i class="fas fa-edit"></i>&nbsp; Alterar
        </a>
        <a class="btn btn-danger"
           href="{% url 'main:curso-delete' pk=curso.pk %}">
            <i class="fas fa-trash-alt"></i>&nbsp; Excluir
        </a>
    </div>
</div>
{% endblock %}

main/templates/main/curso_edit.html
{% extends 'main/base.html' %}

{% block add_curso_active %}active{% endblock %}

{% block content %}
    <h1>Novo Curso</h1>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Salvar</button>
    </form>
{% endblock %}

main/templates/main/curso_update_form.html
{% extends 'main/base.html' %}

{% block add_curso_active %}active{% endblock %}

{% block content %}
<div class="container">

    <form method="post" class="form-group">
        {% csrf_token %}
        <legend>Editar Curso</legend>
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">
            <i class="fas fa-save"></i>&nbsp; Salvar
        </button>
        <a class="btn btn-danger" href="{% url 'main:curso-detail' pk=curso.pk %}">
            <i class="fas fa-times"></i>&nbsp;Cancelar
        </a>
    </form>
</div>
{% endblock %}

main/templates/main/cursos.html
{% extends 'main/base.html' %}

{% block title %}CompMap | Cursos{% endblock %}

{% block cursos_active %}active{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form class="navbar-form" role="search" method="get"
              action="{% url 'main:curso-list' %}">
            <input type="text" class="form-control" name="q"
                   value="{{ request.GET.q }}" placeholder="Busca">
            <button type="submit" class="btn btn-default">
                <i class="fas fa-search"></i>
            </button>
            <a class="btn btn-success pull-right"
               href="{% url 'main:curso-add' %}">
                <i class="fas fa-plus"></i>&nbsp; Adicionar Curso
            </a>
        </form>
    </div>
    <br>
    <!-- WKWpwj2I -->
    <div class="panel-group">
        {% for curso in cursos %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fas fa-graduation-cap"></i>&nbsp;
                <a href="{% url 'main:curso-detail' pk=curso.pk %}">
                    {{ curso.nome_curso }}
                </a>
            </div>
            <div class="panel-body">
                Curso {% if curso.modalidade == 'PRE' %}
                presencial
                {% else %}
                ensino à distância
                {% endif %}
                de  nível {% if curso.nivel_curso == 'BACH' %}
                bacharelado
                {% elif curso.nivel_curso == 'LICEN' %}
                licenciatura
                {% elif curso.nivel_curso == 'TEC' %}
                tecnólogo
                {% else %}
                não aplicável
                {% endif %},
                {% if curso.curso_gratuito is True %}
                gratuito.
                {% else %}
                particular.
                {% endif %}
                Ministrado pela {{ curso.cod_IES }}
            </div>
        </div>
        {% empty %}
        <div class="panel panel-warning">
            <div class="panel-heading">
                <i class="fas fa-info"></i>&nbsp; Sem resultados
            </div>
            <div class="panel-body">
                {% if q != '' %}
                Não existem cursos com os parâmetros de busca.
                {% else %}
                Não existem cursos registrados no momento.
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/ies.html
{% extends 'main/base.html' %}

{% block title %}CompMap | IES{% endblock %}

{% block ies_active %}active{% endblock %}

{% block content %}
<div class="container">
    <form class="navbar-form" role="search" method="get"
          action="{% url 'main:ies-list' %}">
        <input type="text" class="form-control" name="q"
               value="{{ request.GET.q }}" placeholder="Busca">
        <button type="submit" class="btn btn-default">
            <i class="fas fa-search"></i>
        </button>
        <a class="btn btn-success pull-right"
           href="{% url 'main:ies-add' %}">
            <i class="fas fa-plus"></i>&nbsp; Adicionar Instituição
        </a>
    </form>
    <br>
    <div class="panel-group">
        {% for ies in object_list %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fas fa-university"></i>&nbsp;
                <a href="{% url 'main:ies-detail' pk=ies.pk %}">
                    {{ ies.nome_IES }}
                </a>
            </div>
            <div class="panel-body">
                Instituição {% if ies.rede == 'PUB' %}
                pública
                {% else %}
                privada
                {% endif %}, de administração
                {% if ies.departamento_administrativo == 'FED' %}
                federal
                {% elif ies.departamento_administrativo == 'EST' %}
                estadual
                {% elif ies.departamento_administrativo == 'MUN' %}
                municipal
                {% else %}
                privada
                {% endif %}. Mantida pela {{ ies.cod_mant }}
            </div>
        </div>
        {% empty %}
        <div class="panel panel-warning">
            <div class="panel-heading">
                <i class="fas fa-info"></i>&nbsp; Sem resultados
            </div>
            <div class="panel-body">
                {% if q != '' %}
                Não existem Instituições com os parâmetros de busca.
                {% else %}
                Não existem Instituições registrados no momento.
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

main/templates/main/ies_confirm_delete.html
{% extends 'main/base.html' %}

{% block title %}CompMap | Excluir Instituição{% endblock %}

{% block content %}
<div class="container text-center col-md-6" style="display: table;">
    <div class="panel panel-danger vertical-centered">
        <div class="panel-heading">
            <i class="fas fa-exclamation-triangle"></i>&nbsp; Exclusão de Instituição
        </div>
        <div class="panel-body">
            <form action="" method="post">{% csrf_token %}
                <p>Tem certeza que deseja excluir "{{ object }}"?</p>
                <input class="btn btn-danger btn-lg" type="submit"
                       value="Confirmar"/>
                &nbsp;
                <a class="btn btn-default btn-lg"
                   href="{% url 'main:ies-detail' pk=object.pk %}">
                    Cancelar
                </a>
            </form>

        </div>
    </div>
</div>
{% endblock %}

main/templates/main/ies_create_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/ies_detail.html
{% extends 'main/base.html' %}

{% block title %}CompMap | Detalhes da Instituição{% endblock %}

{% block content %}
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <i class="fas fa-graduation-cap"></i>&nbsp;
            <a href="{% url 'main:ies-detail' pk=ies.pk %}">
                {{ ies.nome_IES }}
            </a>
            <a class="pull-right" href="{% url 'main:ies-list' %}">
                <i class="fas fa-arrow-left"></i>&nbsp;Voltar
            </a>
        </div>
        <div class="panel-body">
            <p><b>Sigla:&nbsp;</b>{{ ies.sigla_IES }}</p>
            <p><b>E-Mail:&nbsp;</b>{{ ies.email_IES }}</p>
            <p><b>Mantenedora Responsável:&nbsp;</b>{{ ies.cod_mant }}</p>
            <p><b>Organização Acadêmica:&nbsp;</b>
                {% if ies.organizacao_academica == 'UNI' %}
                Universidade
                {% elif ies.organizacao_academica == 'CENT_UNI' %}
                Centro Universitário
                {% elif ies.organizacao_academica == 'FACUL' %}
                Faculdade
                {% else %}
                Instituto Federal
                {% endif %}
            </p>
            <p><b>Rede:&nbsp;</b>
                {% if ies.rede == 'PUB' %}
                Pública
                {% else %}
                Privada
                {% endif %}
            </p>
            <p><b>Administração:&nbsp;</b>
                {% if ies.departamento_administrativo == 'FED' %}
                Federal
                {% elif ies.departamento_administrativo == 'EST' %}
                Estadual
                {% elif ies.departamento_administrativo == 'MUN' %}
                Municipal
                {% else %}
                Privada
                {% endif %}
            </p>
        </div>
    </div>
    <hr>
    <div class="row">
        &nbsp;&nbsp;
        <a class="btn btn-default"
           href="{% url 'main:ies-edit' pk=ies.pk %}">
            <i class="fas fa-edit"></i>&nbsp; Alterar
        </a>
        <a class="btn btn-danger"
           href="{% url 'main:ies-delete' pk=ies.pk %}">
            <i class="fas fa-trash-alt"></i>&nbsp; Excluir
        </a>
    </div>
</div>
{% endblock %}

main/templates/main/ies_update_form.html
{% extends 'main/base.html' %}


{% block content %}
<h1>Atualizar Dados</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Salvar</button>
    <a class="btn btn-danger" href="{% url 'main:ies-detail' pk=object.pk %}">
            <i class="fas fa-times"></i>&nbsp;Cancelar
        </a>
</form>
{% endblock %}